/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DBJNI {
  public final static native long PlanDB_get_instance();
  public final static native boolean PlanDB_populate_db(long jarg1, PlanDB jarg1_, String jarg2);
  public final static native void PlanDB_destroy_db(long jarg1, PlanDB jarg1_);
  public final static native void PlanDB_clean_db(long jarg1, PlanDB jarg1_);
}
