/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class DTMCPartitionedStates {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DTMCPartitionedStates(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DTMCPartitionedStates obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_DTMCPartitionedStates(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DTMCPartitionedStates(long numberOfStates) {
    this(pladaptJNI.new_DTMCPartitionedStates(numberOfStates), true);
  }

  public void setTransitionProbability(long from, long to, double probability) {
    pladaptJNI.DTMCPartitionedStates_setTransitionProbability(swigCPtr, this, from, to, probability);
  }

  public void assignToPart(long partIndex, long state) {
    pladaptJNI.DTMCPartitionedStates_assignToPart(swigCPtr, this, partIndex, state);
  }

  public long getNumberOfParts() {
    return pladaptJNI.DTMCPartitionedStates_getNumberOfParts(swigCPtr, this);
  }

  public boolean isLastPartFinal() {
    return pladaptJNI.DTMCPartitionedStates_isLastPartFinal(swigCPtr, this);
  }

}
