/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class Environment {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Environment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Environment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_Environment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pladaptJNI.Environment_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pladaptJNI.Environment_change_ownership(this, swigCPtr, true);
  }

  public Environment swigFindRealImpl() {
     Object o = swigOriginalObject();
     if (o != null) {
     	return (Environment)o;
     } else {
	    Environment ret = (Environment) this; // default if it's the base class
	    int type = pladaptJNI.Environment_getType(swigCPtr, null);
	    switch (type) {
	       case Environment.EnvironmentClass.C_ENVIRONMENT:
	    	 break;
	       case Environment.EnvironmentClass.C_GENERIC_ENVIRONMENT:
	         ret = new GenericEnvironment(swigCPtr, swigCMemOwn);
	         break;
	       case Environment.EnvironmentClass.C_JOINT_ENVIRONMENT:
	         ret = new JointEnvironment(swigCPtr, swigCMemOwn);
	         break;
	      default:
	        System.out.println("Instance of unknown Environment class found");
	        break;
		}
      	return ret;
     }
  }

  public long getNumberOfComponents() {
    return (getClass() == Environment.class) ? pladaptJNI.Environment_getNumberOfComponents(swigCPtr, this) : pladaptJNI.Environment_getNumberOfComponentsSwigExplicitEnvironment(swigCPtr, this);
  }

  public Environment getComponent(long c) {
    return new Environment((getClass() == Environment.class) ? pladaptJNI.Environment_getComponent(swigCPtr, this, c) : pladaptJNI.Environment_getComponentSwigExplicitEnvironment(swigCPtr, this, c), false);
  }

  public double asDouble() {
    return (getClass() == Environment.class) ? pladaptJNI.Environment_asDouble(swigCPtr, this) : pladaptJNI.Environment_asDoubleSwigExplicitEnvironment(swigCPtr, this);
  }

  public int getType() {
    return (getClass() == Environment.class) ? pladaptJNI.Environment_getType(swigCPtr, this) : pladaptJNI.Environment_getTypeSwigExplicitEnvironment(swigCPtr, this);
  }

  public java.lang.Object swigOriginalObject() {
    return pladaptJNI.Environment_swigOriginalObject(swigCPtr, this);
  }

  public String toString() {
    return pladaptJNI.Environment_toString(swigCPtr, this);
  }

  public Environment() {
    this(pladaptJNI.new_Environment(), true);
    pladaptJNI.Environment_director_connect(this, swigCPtr, true, true);
  }

  public final static class EnvironmentClass {
    public final static int C_ENVIRONMENT = 0;
    public final static int C_JOINT_ENVIRONMENT = C_ENVIRONMENT + 1;
    public final static int C_GENERIC_ENVIRONMENT = C_JOINT_ENVIRONMENT + 1;
  }

}
