/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class GenericEnvironmentDTMCPartitioned extends EnvironmentDTMCPartitioned {
  private transient long swigCPtr;

  protected GenericEnvironmentDTMCPartitioned(long cPtr, boolean cMemoryOwn) {
    super(pladaptJNI.GenericEnvironmentDTMCPartitioned_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GenericEnvironmentDTMCPartitioned obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_GenericEnvironmentDTMCPartitioned(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GenericEnvironmentDTMCPartitioned(long numberOfStates) {
    this(pladaptJNI.new_GenericEnvironmentDTMCPartitioned(numberOfStates), true);
  }

  public void setStateValue(long state, GenericEnvironment value) {
    pladaptJNI.GenericEnvironmentDTMCPartitioned_setStateValue(swigCPtr, this, state, GenericEnvironment.getCPtr(value), value);
  }

}
