/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class GenericUtilityFunction extends UtilityFunction {
  private transient long swigCPtr;

  protected GenericUtilityFunction(long cPtr, boolean cMemoryOwn) {
    super(pladaptJNI.GenericUtilityFunction_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GenericUtilityFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_GenericUtilityFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pladaptJNI.GenericUtilityFunction_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pladaptJNI.GenericUtilityFunction_change_ownership(this, swigCPtr, true);
  }

  public double getGenAdditiveUtility(GenericConfiguration config, GenericEnvironment environment, int time) {
    return (getClass() == GenericUtilityFunction.class) ? pladaptJNI.GenericUtilityFunction_getGenAdditiveUtility(swigCPtr, this, GenericConfiguration.getCPtr(config), config, GenericEnvironment.getCPtr(environment), environment, time) : pladaptJNI.GenericUtilityFunction_getGenAdditiveUtilitySwigExplicitGenericUtilityFunction(swigCPtr, this, GenericConfiguration.getCPtr(config), config, GenericEnvironment.getCPtr(environment), environment, time);
  }

  public double getGenMultiplicativeUtility(GenericConfiguration config, GenericEnvironment environment, int time) {
    return (getClass() == GenericUtilityFunction.class) ? pladaptJNI.GenericUtilityFunction_getGenMultiplicativeUtility(swigCPtr, this, GenericConfiguration.getCPtr(config), config, GenericEnvironment.getCPtr(environment), environment, time) : pladaptJNI.GenericUtilityFunction_getGenMultiplicativeUtilitySwigExplicitGenericUtilityFunction(swigCPtr, this, GenericConfiguration.getCPtr(config), config, GenericEnvironment.getCPtr(environment), environment, time);
  }

  public double getGenFinalReward(GenericConfiguration config, GenericEnvironment environment, int time) {
    return (getClass() == GenericUtilityFunction.class) ? pladaptJNI.GenericUtilityFunction_getGenFinalReward(swigCPtr, this, GenericConfiguration.getCPtr(config), config, GenericEnvironment.getCPtr(environment), environment, time) : pladaptJNI.GenericUtilityFunction_getGenFinalRewardSwigExplicitGenericUtilityFunction(swigCPtr, this, GenericConfiguration.getCPtr(config), config, GenericEnvironment.getCPtr(environment), environment, time);
  }

  public double getGenAdaptationReward(GenericConfiguration from, GenericConfiguration to, int time) {
    return (getClass() == GenericUtilityFunction.class) ? pladaptJNI.GenericUtilityFunction_getGenAdaptationReward(swigCPtr, this, GenericConfiguration.getCPtr(from), from, GenericConfiguration.getCPtr(to), to, time) : pladaptJNI.GenericUtilityFunction_getGenAdaptationRewardSwigExplicitGenericUtilityFunction(swigCPtr, this, GenericConfiguration.getCPtr(from), from, GenericConfiguration.getCPtr(to), to, time);
  }

  public GenericUtilityFunction() {
    this(pladaptJNI.new_GenericUtilityFunction(), true);
    pladaptJNI.GenericUtilityFunction_director_connect(this, swigCPtr, true, true);
  }

}
