/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class JointEnvironment extends Environment {
  private transient long swigCPtr;

  protected JointEnvironment(long cPtr, boolean cMemoryOwn) {
    super(pladaptJNI.JointEnvironment_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JointEnvironment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_JointEnvironment(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pladaptJNI.JointEnvironment_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pladaptJNI.JointEnvironment_change_ownership(this, swigCPtr, true);
  }

  public JointEnvironment(SWIGTYPE_p_std__shared_ptrT_pladapt__Environment_t componentA, SWIGTYPE_p_std__shared_ptrT_pladapt__Environment_t componentB) {
    this(pladaptJNI.new_JointEnvironment(SWIGTYPE_p_std__shared_ptrT_pladapt__Environment_t.getCPtr(componentA), SWIGTYPE_p_std__shared_ptrT_pladapt__Environment_t.getCPtr(componentB)), true);
    pladaptJNI.JointEnvironment_director_connect(this, swigCPtr, true, true);
  }

  public long getNumberOfComponents() {
    return (getClass() == JointEnvironment.class) ? pladaptJNI.JointEnvironment_getNumberOfComponents(swigCPtr, this) : pladaptJNI.JointEnvironment_getNumberOfComponentsSwigExplicitJointEnvironment(swigCPtr, this);
  }

  public Environment getComponent(long c) {
    return new Environment((getClass() == JointEnvironment.class) ? pladaptJNI.JointEnvironment_getComponent(swigCPtr, this, c) : pladaptJNI.JointEnvironment_getComponentSwigExplicitJointEnvironment(swigCPtr, this, c), false);
  }

  public int getType() {
    return (getClass() == JointEnvironment.class) ? pladaptJNI.JointEnvironment_getType(swigCPtr, this) : pladaptJNI.JointEnvironment_getTypeSwigExplicitJointEnvironment(swigCPtr, this);
  }

}
