/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class pladapt implements pladaptConstants {
  public static double testGeneric(GenericUtilityFunction u, GenericConfiguration c, GenericEnvironment e) {
    return pladaptJNI.testGeneric(GenericUtilityFunction.getCPtr(u), u, GenericConfiguration.getCPtr(c), c, GenericEnvironment.getCPtr(e), e);
  }

  public static double testUtilityFunction(UtilityFunction u, Configuration c, Environment e) {
    return pladaptJNI.testUtilityFunction(UtilityFunction.getCPtr(u), u, Configuration.getCPtr(c), c, Environment.getCPtr(e), e);
  }

  public static double testUtilityFunctionWithConfigMgr(UtilityFunction u, GenericConfigurationManager cm, Environment e) {
    return pladaptJNI.testUtilityFunctionWithConfigMgr(UtilityFunction.getCPtr(u), u, GenericConfigurationManager.getCPtr(cm), cm, Environment.getCPtr(e), e);
  }

}
