/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class SDPAdaptationManager extends AdaptationManager {
  private transient long swigCPtr;

  protected SDPAdaptationManager(long cPtr, boolean cMemoryOwn) {
    super(pladaptJNI.SDPAdaptationManager_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDPAdaptationManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_SDPAdaptationManager(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String getNO_LATENCY() {
    return pladaptJNI.SDPAdaptationManager_NO_LATENCY_get();
  }

  public static String getREACH_OPTIONS() {
    return pladaptJNI.SDPAdaptationManager_REACH_OPTIONS_get();
  }

  public static String getREACH_PATH() {
    return pladaptJNI.SDPAdaptationManager_REACH_PATH_get();
  }

  public static String getREACH_PREFIX() {
    return pladaptJNI.SDPAdaptationManager_REACH_PREFIX_get();
  }

  public static String getREACH_MODEL() {
    return pladaptJNI.SDPAdaptationManager_REACH_MODEL_get();
  }

  public static String getREACH_SCOPE() {
    return pladaptJNI.SDPAdaptationManager_REACH_SCOPE_get();
  }

  public SDPAdaptationManager() {
    this(pladaptJNI.new_SDPAdaptationManager(), true);
  }

  public boolean supportsStrategy() {
    return pladaptJNI.SDPAdaptationManager_supportsStrategy(swigCPtr, this);
  }

  public SWIGTYPE_p_std__shared_ptrT_std__listT_std__setT_std__string_t_t_t getStrategy() {
    return new SWIGTYPE_p_std__shared_ptrT_std__listT_std__setT_std__string_t_t_t(pladaptJNI.SDPAdaptationManager_getStrategy(swigCPtr, this), true);
  }

}
