/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class TimeSeriesPredictor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TimeSeriesPredictor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TimeSeriesPredictor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_TimeSeriesPredictor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static TimeSeriesPredictor getInstance(StringVector modelArgs, long trainingLength, long horizon) {
    long cPtr = pladaptJNI.TimeSeriesPredictor_getInstance__SWIG_0(StringVector.getCPtr(modelArgs), modelArgs, trainingLength, horizon);
    return (cPtr == 0) ? null : new TimeSeriesPredictor(cPtr, false);
  }

  public static TimeSeriesPredictor getInstance(String model, long trainingLength, long horizon) {
    long cPtr = pladaptJNI.TimeSeriesPredictor_getInstance__SWIG_1(model, trainingLength, horizon);
    return (cPtr == 0) ? null : new TimeSeriesPredictor(cPtr, false);
  }

  public long getTrainingLength() {
    return pladaptJNI.TimeSeriesPredictor_getTrainingLength(swigCPtr, this);
  }

  public void observe(double v) {
    pladaptJNI.TimeSeriesPredictor_observe(swigCPtr, this, v);
  }

  public void predict(long n, double[] predictions, double[] variances) {
    pladaptJNI.TimeSeriesPredictor_predict__SWIG_0(swigCPtr, this, n, predictions, variances);
  }

  public void predict(long n, double[] predictions) {
    pladaptJNI.TimeSeriesPredictor_predict__SWIG_1(swigCPtr, this, n, predictions);
  }

  public TimeSeriesPredictor clone() {
    long cPtr = pladaptJNI.TimeSeriesPredictor_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new TimeSeriesPredictor(cPtr, false);
  }

  public void predict(double lowerBound, double upperBound, long n, double[] predictions, double[] variances) {
    pladaptJNI.TimeSeriesPredictor_predict__SWIG_2(swigCPtr, this, lowerBound, upperBound, n, predictions, variances);
  }

  public void predict(double lowerBound, double upperBound, long n, double[] predictions) {
    pladaptJNI.TimeSeriesPredictor_predict__SWIG_3(swigCPtr, this, lowerBound, upperBound, n, predictions);
  }

  public EnvironmentDTMCPartitioned generateEnvironmentDTMC(long branchingDepth, long depth, double lowerBound) {
    return new EnvironmentDTMCPartitioned(pladaptJNI.TimeSeriesPredictor_generateEnvironmentDTMC__SWIG_0(swigCPtr, this, branchingDepth, depth, lowerBound), true);
  }

  public EnvironmentDTMCPartitioned generateEnvironmentDTMC(long branchingDepth, long depth) {
    return new EnvironmentDTMCPartitioned(pladaptJNI.TimeSeriesPredictor_generateEnvironmentDTMC__SWIG_1(swigCPtr, this, branchingDepth, depth), true);
  }

  public EnvironmentDTMCPartitioned generateEnvironmentDTMC(long branchingDepth) {
    return new EnvironmentDTMCPartitioned(pladaptJNI.TimeSeriesPredictor_generateEnvironmentDTMC__SWIG_2(swigCPtr, this, branchingDepth), true);
  }

}
