/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class AdaptationPlanner {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AdaptationPlanner(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AdaptationPlanner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        APJNI.delete_AdaptationPlanner(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AdaptationPlanner() {
    this(APJNI.new_AdaptationPlanner(), true);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t plan(String environmentModel, String initialState, SWIGTYPE_p_std__string path, boolean returnPlan) {
    return new SWIGTYPE_p_std__vectorT_std__string_t(APJNI.AdaptationPlanner_plan__SWIG_0(swigCPtr, this, environmentModel, initialState, SWIGTYPE_p_std__string.getCPtr(path), returnPlan), true);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t plan(String environmentModel, String initialState, SWIGTYPE_p_std__string path) {
    return new SWIGTYPE_p_std__vectorT_std__string_t(APJNI.AdaptationPlanner_plan__SWIG_1(swigCPtr, this, environmentModel, initialState, SWIGTYPE_p_std__string.getCPtr(path)), true);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t plan(String environmentModel, String initialState) {
    return new SWIGTYPE_p_std__vectorT_std__string_t(APJNI.AdaptationPlanner_plan__SWIG_2(swigCPtr, this, environmentModel, initialState), true);
  }

  public void setModelTemplatePath(String modelTemplatePath) {
    APJNI.AdaptationPlanner_setModelTemplatePath(swigCPtr, this, modelTemplatePath);
  }

  public void test() {
    APJNI.AdaptationPlanner_test(swigCPtr, this);
  }

}
