/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class APJNI {
  public final static native long getActions(String jarg1, String jarg2, long jarg3);
  public final static native long getNowStates(String jarg1);
  public final static native long new_AdaptationPlanner();
  public final static native long AdaptationPlanner_plan__SWIG_0(long jarg1, AdaptationPlanner jarg1_, String jarg2, String jarg3, long jarg4, boolean jarg5);
  public final static native long AdaptationPlanner_plan__SWIG_1(long jarg1, AdaptationPlanner jarg1_, String jarg2, String jarg3, long jarg4);
  public final static native long AdaptationPlanner_plan__SWIG_2(long jarg1, AdaptationPlanner jarg1_, String jarg2, String jarg3);
  public final static native void AdaptationPlanner_setModelTemplatePath(long jarg1, AdaptationPlanner jarg1_, String jarg2);
  public final static native void delete_AdaptationPlanner(long jarg1);
  public final static native void AdaptationPlanner_test(long jarg1, AdaptationPlanner jarg1_);
}
