/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class Configuration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Configuration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Configuration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_Configuration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pladaptJNI.Configuration_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pladaptJNI.Configuration_change_ownership(this, swigCPtr, true);
  }

  public Configuration swigFindRealImpl() {
     Object o = swigOriginalObject();
     if (o != null) {
     	return (Configuration)o;
     } else {
	    Configuration ret = (Configuration) this; // default if it's the base class
	    int type = pladaptJNI.Configuration_getType(swigCPtr, null);
	    switch (type) {
	       case Configuration.ConfigurationClass.C_CONFIGURATION:
	    	 break;
	       case Configuration.ConfigurationClass.C_GENERIC_CONFIGURATION:
	         ret = new GenericConfiguration(swigCPtr, swigCMemOwn);
	         break;
	      default:
	        System.out.println("Instance of unknown Configuration class found");
	        break;
		}
      	return ret;
     }
  }

  public int getType() {
    return (getClass() == Configuration.class) ? pladaptJNI.Configuration_getType(swigCPtr, this) : pladaptJNI.Configuration_getTypeSwigExplicitConfiguration(swigCPtr, this);
  }

  protected boolean equals(Configuration other) {
    return pladaptJNI.Configuration_equals(swigCPtr, this, Configuration.getCPtr(other), other);
  }

  public java.lang.Object swigOriginalObject() {
    return pladaptJNI.Configuration_swigOriginalObject(swigCPtr, this);
  }

  public String toString() {
    return pladaptJNI.Configuration_toString(swigCPtr, this);
  }

  public Configuration() {
    this(pladaptJNI.new_Configuration(), true);
    pladaptJNI.Configuration_director_connect(this, swigCPtr, true, true);
  }

  public final static class ConfigurationClass {
    public final static int C_CONFIGURATION = 0;
    public final static int C_GENERIC_CONFIGURATION = C_CONFIGURATION + 1;
  }

}
