/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class GenericConfigurationManager {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected GenericConfigurationManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GenericConfigurationManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_GenericConfigurationManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GenericConfiguration getConfigurationTemplate() {
    return new GenericConfiguration(pladaptJNI.GenericConfigurationManager_getConfigurationTemplate(swigCPtr, this), false);
  }

  public GenericConfiguration addNewConfiguration() {
    return new GenericConfiguration(pladaptJNI.GenericConfigurationManager_addNewConfiguration(swigCPtr, this), false);
  }

  public GenericConfigurationManager() {
    this(pladaptJNI.new_GenericConfigurationManager(), true);
  }

}
