/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class GenericEnvironment extends Environment {
  private transient long swigCPtr;

  protected GenericEnvironment(long cPtr, boolean cMemoryOwn) {
    super(pladaptJNI.GenericEnvironment_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GenericEnvironment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_GenericEnvironment(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pladaptJNI.GenericEnvironment_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pladaptJNI.GenericEnvironment_change_ownership(this, swigCPtr, true);
  }

  public GenericEnvironment() {
    this(pladaptJNI.new_GenericEnvironment__SWIG_0(), true);
    pladaptJNI.GenericEnvironment_director_connect(this, swigCPtr, true, true);
  }

  public GenericEnvironment(String doubleProperty) {
    this(pladaptJNI.new_GenericEnvironment__SWIG_1(doubleProperty), true);
    pladaptJNI.GenericEnvironment_director_connect(this, swigCPtr, true, true);
  }

  public double asDouble() {
    return (getClass() == GenericEnvironment.class) ? pladaptJNI.GenericEnvironment_asDouble(swigCPtr, this) : pladaptJNI.GenericEnvironment_asDoubleSwigExplicitGenericEnvironment(swigCPtr, this);
  }

  public int getType() {
    return (getClass() == GenericEnvironment.class) ? pladaptJNI.GenericEnvironment_getType(swigCPtr, this) : pladaptJNI.GenericEnvironment_getTypeSwigExplicitGenericEnvironment(swigCPtr, this);
  }

  public boolean isEqual(GenericEnvironment other) {
    return pladaptJNI.GenericEnvironment_isEqual(swigCPtr, this, GenericEnvironment.getCPtr(other), other);
  }

  protected boolean equals(Environment other) {
    return (getClass() == GenericEnvironment.class) ? pladaptJNI.GenericEnvironment_equals(swigCPtr, this, Environment.getCPtr(other), other) : pladaptJNI.GenericEnvironment_equalsSwigExplicitGenericEnvironment(swigCPtr, this, Environment.getCPtr(other), other);
  }

  public String toString() {
    return pladaptJNI.GenericEnvironment_toString(swigCPtr, this);
  }

}
