/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class GenericConfiguration extends Configuration {
  private transient long swigCPtr;

  protected GenericConfiguration(long cPtr, boolean cMemoryOwn) {
    super(pladaptJNI.GenericConfiguration_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GenericConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_GenericConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pladaptJNI.GenericConfiguration_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pladaptJNI.GenericConfiguration_change_ownership(this, swigCPtr, true);
  }

  public boolean isEqual(GenericConfiguration other) {
    return pladaptJNI.GenericConfiguration_isEqual(swigCPtr, this, GenericConfiguration.getCPtr(other), other);
  }

  public int getType() {
    return (getClass() == GenericConfiguration.class) ? pladaptJNI.GenericConfiguration_getType(swigCPtr, this) : pladaptJNI.GenericConfiguration_getTypeSwigExplicitGenericConfiguration(swigCPtr, this);
  }

  protected boolean equals(Configuration other) {
    return (getClass() == GenericConfiguration.class) ? pladaptJNI.GenericConfiguration_equals(swigCPtr, this, Configuration.getCPtr(other), other) : pladaptJNI.GenericConfiguration_equalsSwigExplicitGenericConfiguration(swigCPtr, this, Configuration.getCPtr(other), other);
  }

  public String toString() {
    return pladaptJNI.GenericConfiguration_toString(swigCPtr, this);
  }

  public GenericConfiguration() {
    this(pladaptJNI.new_GenericConfiguration(), true);
    pladaptJNI.GenericConfiguration_director_connect(this, swigCPtr, true, true);
  }

}
