/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class JavaSDPAdaptationManager extends SDPAdaptationManager {
  private transient long swigCPtr;

  protected JavaSDPAdaptationManager(long cPtr, boolean cMemoryOwn) {
    super(pladaptJNI.JavaSDPAdaptationManager_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JavaSDPAdaptationManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_JavaSDPAdaptationManager(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void initialize(GenericConfigurationManager configMgr, String YAMLParams) {
    pladaptJNI.JavaSDPAdaptationManager_initialize(swigCPtr, this, GenericConfigurationManager.getCPtr(configMgr), configMgr, YAMLParams);
  }

  public StringVector evaluate(Configuration currentConfigObj, EnvironmentDTMCPartitioned envDTMC, UtilityFunction utilityFunction, long horizon) {
    return new StringVector(pladaptJNI.JavaSDPAdaptationManager_evaluate(swigCPtr, this, Configuration.getCPtr(currentConfigObj), currentConfigObj, EnvironmentDTMCPartitioned.getCPtr(envDTMC), envDTMC, UtilityFunction.getCPtr(utilityFunction), utilityFunction, horizon), true);
  }

  public JavaSDPAdaptationManager() {
    this(pladaptJNI.new_JavaSDPAdaptationManager(), true);
  }

}
