/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public interface pladaptConstants {
  public final static int PLADAPT_SDP_NOPARTITION = 0;
  public final static int SUPPORTS_GET_STRATEGY = 1;
}
