/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class PMCAdaptationManager extends AdaptationManager {
  private transient long swigCPtr;

  protected PMCAdaptationManager(long cPtr, boolean cMemoryOwn) {
    super(pladaptJNI.PMCAdaptationManager_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PMCAdaptationManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_PMCAdaptationManager(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String generateEnvironmentDTMC(EnvironmentDTMCPartitioned envDTMC) {
    return pladaptJNI.PMCAdaptationManager_generateEnvironmentDTMC(EnvironmentDTMCPartitioned.getCPtr(envDTMC), envDTMC);
  }

  public static void setNO_LATENCY(String value) {
    pladaptJNI.PMCAdaptationManager_NO_LATENCY_set(value);
  }

  public static String getNO_LATENCY() {
    return pladaptJNI.PMCAdaptationManager_NO_LATENCY_get();
  }

  public static void setTEMPLATE_PATH(String value) {
    pladaptJNI.PMCAdaptationManager_TEMPLATE_PATH_set(value);
  }

  public static String getTEMPLATE_PATH() {
    return pladaptJNI.PMCAdaptationManager_TEMPLATE_PATH_get();
  }

  public PMCAdaptationManager() {
    this(pladaptJNI.new_PMCAdaptationManager(), true);
  }

}
