/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pladapt;

public class UtilityFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UtilityFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UtilityFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pladaptJNI.delete_UtilityFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pladaptJNI.UtilityFunction_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pladaptJNI.UtilityFunction_change_ownership(this, swigCPtr, true);
  }

  public double getAdditiveUtility(Configuration config, Environment environment, int time) {
    return (getClass() == UtilityFunction.class) ? pladaptJNI.UtilityFunction_getAdditiveUtility(swigCPtr, this, Configuration.getCPtr(config), config, Environment.getCPtr(environment), environment, time) : pladaptJNI.UtilityFunction_getAdditiveUtilitySwigExplicitUtilityFunction(swigCPtr, this, Configuration.getCPtr(config), config, Environment.getCPtr(environment), environment, time);
  }

  public double getMultiplicativeUtility(Configuration config, Environment environment, int time) {
    return (getClass() == UtilityFunction.class) ? pladaptJNI.UtilityFunction_getMultiplicativeUtility(swigCPtr, this, Configuration.getCPtr(config), config, Environment.getCPtr(environment), environment, time) : pladaptJNI.UtilityFunction_getMultiplicativeUtilitySwigExplicitUtilityFunction(swigCPtr, this, Configuration.getCPtr(config), config, Environment.getCPtr(environment), environment, time);
  }

  public double getFinalReward(Configuration config, Environment environment, int time) {
    return (getClass() == UtilityFunction.class) ? pladaptJNI.UtilityFunction_getFinalReward(swigCPtr, this, Configuration.getCPtr(config), config, Environment.getCPtr(environment), environment, time) : pladaptJNI.UtilityFunction_getFinalRewardSwigExplicitUtilityFunction(swigCPtr, this, Configuration.getCPtr(config), config, Environment.getCPtr(environment), environment, time);
  }

  public double getAdaptationReward(Configuration from, Configuration to, int time) {
    return (getClass() == UtilityFunction.class) ? pladaptJNI.UtilityFunction_getAdaptationReward(swigCPtr, this, Configuration.getCPtr(from), from, Configuration.getCPtr(to), to, time) : pladaptJNI.UtilityFunction_getAdaptationRewardSwigExplicitUtilityFunction(swigCPtr, this, Configuration.getCPtr(from), from, Configuration.getCPtr(to), to, time);
  }

  public UtilityFunction() {
    this(pladaptJNI.new_UtilityFunction(), true);
    pladaptJNI.UtilityFunction_director_connect(this, swigCPtr, true, true);
  }

}
