/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TSPJNI {
  public final static native long TimeSeriesPredictor_getInstance__SWIG_0(long jarg1, long jarg2, long jarg3);
  public final static native long TimeSeriesPredictor_getInstance__SWIG_1(String jarg1, long jarg2, long jarg3);
  public final static native long TimeSeriesPredictor_getTrainingLength(long jarg1, TimeSeriesPredictor jarg1_);
  public final static native void TimeSeriesPredictor_observe(long jarg1, TimeSeriesPredictor jarg1_, double jarg2);
  public final static native void TimeSeriesPredictor_predict__SWIG_0(long jarg1, TimeSeriesPredictor jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native void TimeSeriesPredictor_predict__SWIG_1(long jarg1, TimeSeriesPredictor jarg1_, long jarg2, long jarg3);
  public final static native long TimeSeriesPredictor_clone(long jarg1, TimeSeriesPredictor jarg1_);
  public final static native long TimeSeriesPredictor_createScenarioTree__SWIG_0(long jarg1, TimeSeriesPredictor jarg1_, long jarg2, long jarg3);
  public final static native long TimeSeriesPredictor_createScenarioTree__SWIG_1(long jarg1, TimeSeriesPredictor jarg1_, long jarg2);
  public final static native void TimeSeriesPredictor_predict__SWIG_2(long jarg1, TimeSeriesPredictor jarg1_, double jarg2, double jarg3, long jarg4, long jarg5, long jarg6);
  public final static native void TimeSeriesPredictor_predict__SWIG_3(long jarg1, TimeSeriesPredictor jarg1_, double jarg2, double jarg3, long jarg4, long jarg5);
  public final static native long TimeSeriesPredictor_createScenarioTree__SWIG_2(long jarg1, TimeSeriesPredictor jarg1_, double jarg2, double jarg3, long jarg4, long jarg5);
  public final static native long TimeSeriesPredictor_createScenarioTree__SWIG_3(long jarg1, TimeSeriesPredictor jarg1_, double jarg2, double jarg3, long jarg4);
  public final static native void delete_TimeSeriesPredictor(long jarg1);
}
